language: ruby
rvm:
  - 2.2.3
env: COVERAGE=true
after_install:
  - psql -c 'create database travis'
  - psql -c 'create database testrubypdx_test'
branches:
  only:
    - dev
    - staging
    - master
sudo: false
notifications:
  - email: false